/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entities.Animal;
import entities.Cachorro;
import entities.Gato;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author aluno
 */
public class TelaListagemDePets extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaListagemDePets() {
        initComponents();
        exibirListaDeAnimais();
        configurarPlaceHolder(txtBuscarPetPorNome, "Digite o nome...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEncerrarSessao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarPetPorNome = new javax.swing.JTextField();
        btnBuscarPet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaDeAnimais = new javax.swing.JTextArea();
        comboBoxEspecie = new javax.swing.JComboBox<>();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        btnEncerrarSessao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncerrarSessao.setText("X");
        btnEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarSessaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Lista de Pets");

        txtBuscarPetPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPetPorNomeActionPerformed(evt);
            }
        });

        btnBuscarPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPet.setForeground(new java.awt.Color(0, 0, 51));
        btnBuscarPet.setText("BUSCAR");
        btnBuscarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPetActionPerformed(evt);
            }
        });

        txtListaDeAnimais.setBackground(new java.awt.Color(0, 0, 51));
        txtListaDeAnimais.setColumns(20);
        txtListaDeAnimais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtListaDeAnimais.setForeground(new java.awt.Color(255, 255, 255));
        txtListaDeAnimais.setRows(5);
        jScrollPane1.setViewportView(txtListaDeAnimais);

        comboBoxEspecie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboBoxEspecie.setForeground(new java.awt.Color(0, 0, 51));
        comboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "GATOS", "CACHORROS" }));
        comboBoxEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEspecieActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(0, 0, 51));
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 51));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desenvolvido por @AbrigoPet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscarPetPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(comboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPetPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void configurarPlaceHolder(JTextField txt, String mensagem) {
        txt.setText(mensagem);
        txt.setForeground(Color.GRAY);

        txt.addFocusListener(new FocusListener() {

            public void focusGained(FocusEvent e) {
                if (txt.getText().equals(mensagem)) {
                    txt.setText("");
                    txt.setForeground(Color.BLACK); // Cor do texto normal
                }
            }

            public void focusLost(FocusEvent e) {
                if (txt.getText().isEmpty()) {
                    txt.setText(mensagem);
                    txt.setForeground(Color.GRAY); // Cor do placeholder
                }
            }
        });

    }

    private void btnEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarSessaoActionPerformed
        dispose();
    }//GEN-LAST:event_btnEncerrarSessaoActionPerformed

    public void exibirListaDeAnimais() {
        txtListaDeAnimais.setText(Animal.listarAnimais());
    }
    private void txtBuscarPetPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPetPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPetPorNomeActionPerformed

    private void btnBuscarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPetActionPerformed
        String nome = txtBuscarPetPorNome.getText();
        if (nome.equalsIgnoreCase("Digite o nome...")) {
            JOptionPane.showMessageDialog(rootPane, "O campo de busca deve ser preenchido");
        } else {
            Animal animal = Animal.buscarPorNome(nome);
            if (animal != null) {
                txtListaDeAnimais.setText(animal.toString());
            } else {
                txtListaDeAnimais.setText("Animal não encontrado");
            }
        }


    }//GEN-LAST:event_btnBuscarPetActionPerformed

    private void comboBoxEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEspecieActionPerformed
        int indexEspecie = comboBoxEspecie.getSelectedIndex();
        switch (indexEspecie) {
            case 0:
                txtListaDeAnimais.setText(Animal.listarAnimais());
                break;
            case 1:
                txtListaDeAnimais.setText(Animal.listarAnimaisPorEspecie("GATO"));
                break;
            case 2:
                txtListaDeAnimais.setText(Animal.listarAnimaisPorEspecie("CACHORRO"));
                break;
        }
    }//GEN-LAST:event_comboBoxEspecieActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String nome = txtBuscarPetPorNome.getText();

        if (nome.equalsIgnoreCase("Digite o nome...")) {
            JOptionPane.showMessageDialog(rootPane, "O campo de busca deve ser preenchido");
        } else {
            Animal animal = Animal.buscarPorNome(nome);
            if (Animal.buscarPorNome(nome) == null) {
                JOptionPane.showMessageDialog(null, "Animal não existe");
            } else {
                int escolha = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover " + nome + " ?");
                switch (escolha) {
                    case 0:
                        Animal.listaDeAnimais.remove(animal);
                        JOptionPane.showMessageDialog(null, "Remoção realizada com sucesso");
                        exibirListaDeAnimais();
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(null, "Remoção cancelada");
                        break;
                }
            }
        }


    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String nome = JOptionPane.showInputDialog(rootPane, "digite o nome");
            String novoNome;
            int novaIdade;
            double novoPeso;

            if (Animal.buscarPorNome(nome) != null) {

                do {
                    novoNome = JOptionPane.showInputDialog(rootPane, "Digite o novo nome (min. 3 caracteres)");
                } while (novoNome.length() < 2);

                do {
                    novaIdade = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Digite a nova idade (maior que 0)"));
                } while (novaIdade <= 0);

                do {
                    novoPeso = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Digite a novo peso (maior que 0.00)"));
                } while (novoPeso <= 0);

                Animal.editarAnimal(nome, novoPeso, novaIdade, novoNome);
                JOptionPane.showMessageDialog(null, "Animal Editado com Sucesso");

                exibirListaDeAnimais();

            } else {
                JOptionPane.showMessageDialog(null, "Animal não encontrado");
            }
            exibirListaDeAnimais();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro: Apenas números são permitidos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDePets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDePets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDePets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDePets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*btnRegistrarAdocao Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemDePets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPet;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEncerrarSessao;
    private javax.swing.JComboBox<String> comboBoxEspecie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarPetPorNome;
    private javax.swing.JTextArea txtListaDeAnimais;
    // End of variables declaration//GEN-END:variables
}
